version: '3.3'

services:
  django:
    build:
      context: ../back
      dockerfile: ./Dockerfile

    env_file:
      - common.env
    volumes:
    - ../back/demoapp/:/app
    networks:
      - appnet

networks:
  appnet: