version: '3.3'

services:

  PostgreSQL:
    image: postgres:latest
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: demodb
    ports:
     - "5432:5432"
    networks:
     - appnet

networks:
  appnet:
#  lbnet:
